name: ni
channels:
  - conda-forge
  - defaults
dependencies:
  - Pillow=8.3.0
  - matplotlib=3.4.2
  - numpy=1.20.2
  - pyamg=4.0.0
  - pyvista=0.31.3
  - scipy=1.6.2
  - pip=19.0.3
  - pip:
    - opencv-python==4.5.1.48
    - scikit_learn==0.24.2
